config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'
  resources :books
  resources :borrows, only: [:create, :destroy]
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :borrows, dependent: :destroy
  has_many :users, through: :borrows

  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :isbn, presence: true, uniqueness: true
  validates :total_copies, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def self.search_by_filter(query)
    Book.where(
      "title LIKE :query OR author LIKE :query OR genre LIKE :query",
      { query: "%#{query}%" }
    )
  end

  def available_copies
    total_copies - borrows.where(return_date: nil).count
  end

  def self.sum_total_copies
    sum(:total_copies)
  end

end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validate :book_is_available, on: :create
  validate :user_has_single_borrowed_copy, on: :create

  def book_is_available
    total_amount = Book.find(book_id).total_copies
    borrowed_amount = Borrow.where(book_id: book_id, return_date: nil).count

    if borrowed_amount >= total_amount
      errors.add(:book, 'is not available for borrowing')
    end
  end

  def user_has_single_borrowed_copy
    borrowed_books = Borrow.where(
      user_id: user_id,
      book_id: book_id,
      return_date: nil
    ).count

    if borrowed_books >= 1
      errors.add(:user, 'has already borrowed this book')
    end
  end

  def self.total_borrowed_books
    where(return_date: nil).count
  end

  def self.due_today
    where(due_date: Date.today).includes(:book)
  end

  def self.borrowed_books_by_due_date
    where(return_date: nil).includes(:book, :user).order(due_date: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :borrows, dependent: :destroy
  has_many :books, through: :borrows

  # A member fetches all their borrows
  def fetch_borrows_with_books
    borrows.includes(:book).where(return_date: nil)
  end

  # A librarian fetches all members with overdue books
  def self.with_overdue_books
    joins(:borrows).where('borrows.due_date <= ? AND borrows.return_date IS NULL', Date.today)
                   .distinct
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :permission_denied

  private
  def permission_denied
    flash[:error] = "You don't have the proper permissions to view this page."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_user, only: %i[ new create edit update destroy ]

  # GET /books or /books.json
  def index
    if params[:query].present?
      @books = Book.search_by_filter(params[:query])
    else
      @books = Book.all
    end
    @borrow = Borrow.new
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :genre, :isbn, :total_copies)
    end

    def authorize_user
      book = @book || Book
      authorize book
    end
end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :set_borrow, only: %i[ destroy ]
  before_action :authenticate_user!
  before_action :authorize_user, only: %i[ create destroy ]

  # POST /borrows
  def create
    @borrow = Borrow.new(borrow_params)
    @borrow.borrow_date = Date.today
    @borrow.due_date = Date.today + 2.weeks

    respond_to do |format|
      if @borrow.save
        format.html { redirect_to root_path, notice: "Book was successfully borrowed." }
        format.json { redirect_to root_path, status: :created, location: @borrow }
      else
        format.html { redirect_to root_path, status: :unprocessable_entity }
        format.json { render json: @borrow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrows/1
  def destroy
    @borrow.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: "Book was successfully
returned." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrow
      @borrow = Borrow.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def borrow_params
      params.require(:borrow).permit(:book_id, :user_id)
    end

    def authorize_user
      borrow = @borrow || Borrow
      authorize borrow
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    if current_user && !current_user.admin?
      @borrows_with_books = current_user&.fetch_borrows_with_books
    elsif current_user&.admin?
      @total_books = Book.sum_total_copies
      @total_borrowed_books = Borrow.total_borrowed_books
      @books_due_today = Borrow.due_today
      @members_with_overdue_books = User.with_overdue_books
      @borrowed_books_by_due_date = Borrow.borrowed_books_by_due_date
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/books/_book.html.erb
<td><%= book.title %></td>
<td><%= book.author %></td>
<td><%= book.genre %></td>
<td><%= book.isbn %></td>
<td><%= book.total_copies %></td>

app/views/books/_form.html.erb
<%= form_with(model: book, class: 'margin-bottom-7' ) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='margin-bottom-5'>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class='margin-bottom-5'>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div class='margin-bottom-5'>
    <%= form.label :genre, style: "display: block" %>
    <%= form.text_field :genre %>
  </div>

  <div class='margin-bottom-5'>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div class='margin-bottom-5'>
    <%= form.label :total_copies, style: "display: block" %>
    <%= form.number_field :total_copies %>
  </div>

  <div class='margin-bottom-5'>
    <%= form.submit class: 'btn-blue' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<p style="color: green"><%= notice %></p>
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "View", @book, class: 'btn-green' %> |
  <%= link_to "Back", books_path, class: 'btn-green' %>
</div>

app/views/books/index.html.erb
<% if current_user %>
  <%= link_to "Dashboard", root_path, class: 'btn-purple' %>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: "delete" }, class: 'btn-red' %>
<% end %>
<p style="color: green"><%= notice %></p>

<h1>Books</h1>
<%= link_to "New book", new_book_path, class: 'btn-blue margin-bottom-7' %>

<%= form_with url: books_path, method: :get, local: true do %>
  <div class="field margin-bottom-7">
    <%= label_tag :search, "Search by title, author, or genre:" %>
    <%= text_field_tag :query, params[:query], class: 'form-input' %>
    <%= submit_tag "Search", class: 'btn-green' %>
  </div>
<% end %>

<div id="books" class="wrapper">
  <table>
    <thead>
      <tr class="header">
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th>ISBN</th>
        <th>Copies</th>
        <th></th>
      </tr>
    </thead>
    <% @books.each do |book| %>
      <tr id="<%= dom_id book %>">
        <%= render book %>
        <td data-controller="borrows">
          <%= link_to "View", book, class: 'btn-green'%>
          <% if current_user && !current_user.admin? %>
            <%= form_with(model: @borrow) do |form| %>
              <%= form.submit "Borrow",
                              data: {
                                book_id: book.id,
                                user_id: current_user.id,
                                action: "borrows#create"
                              },
                              class: 'btn-purple'
              %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<p style="color: green"><%= notice %></p>
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path, class: 'btn-green' %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="books" class="wrapper">
  <table>
    <thead>
    <tr class="header">
      <th class="th">Title</th>
      <th class="th">Author</th>
      <th class="th">Genre</th>
      <th class="th">ISBN</th>
      <th class="th">Copies</th>
    </tr>
    </thead>
    <%= render @book %>
  </table>
</div>

<div class="margin-bottom-5">
  <%= link_to "Edit", edit_book_path(@book), class: 'btn-blue' %>
</div>
<div class="margin-bottom-5">
  <%= link_to "Back", books_path, class: 'btn-green' %>
</div>
<div class="margin-bottom-5">
  <%= button_to "Destroy", @book, method: :delete, class: 'btn-red' %>
</div>

app/views/dashboard/_admin_dashboard.html.erb
<h1>Dashboard</h1>

<h2>Total books: <%= @total_books %></h2>
<h2>Total borrowed books: <%= @total_borrowed_books %></h2>
<h2>Books due today:</h2>
<div id="due_today" class="wrapper">
  <table>
    <thead>
      <tr class="header">
        <th>Title</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
      <% @books_due_today.each do |borrow| %>
        <tr>
          <td><%= borrow.book.title %></td>
          <td><%= borrow.book.author %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<h2>Members overdue:</h2>
<div id="members_overdue" class="wrapper">
  <table>
    <thead>
      <tr class="header">
        <th>Member ID</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @members_with_overdue_books.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<h2>List of borrowed books:</h2>
<div id="borrowed_list" class="wrapper">
  <table>
    <thead>
      <tr class="header">
        <th>Title</th>
        <th>Author</th>
        <th>Member ID</th>
        <th>Email</th>
        <th>Due Date</th>
        <th>Return</th>
      </tr>
    </thead>
    <tbody>
      <% @borrowed_books_by_due_date.each do |borrow| %>
        <tr>
          <td><%= borrow.book.title %></td>
          <td><%= borrow.book.author %></td>
          <td><%= borrow.user.id %></td>
          <td><%= borrow.user.email %></td>
          <td><%= borrow.due_date %></td>
          <td>
            <%= button_to "Return", borrow_path(borrow),
                          method: :delete,
                          class: "btn-red" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/_borrow.html.erb
<td><%= borrow.book.title %></td>
<td><%= borrow.book.author %></td>
<td><%= borrow.due_date %></td>
<td><%= (Date.today - borrow.due_date).to_i > 15 ? 'Yes' : 'No' %></td>

app/views/dashboard/_user_dashboard.html.erb
<h1>Dashboard</h1>

<% if @borrows_with_books.size > 0 %>
<h2>Your borrowed books</h2>
  <div id="borrows" class="wrapper">
    <table>
      <thead>
      <tr class="header">
        <th>Title</th>
        <th>Author</th>
        <th>Due Date</th>
        <th>Overdue?</th>
      </tr>
      </thead>
      <% @borrows_with_books.each do |borrow| %>
        <tr id="<%= dom_id borrow %>">
          <%= render partial: 'borrow', locals: {borrow: borrow} %>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/dashboard/home.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Check out our books", books_path, class: 'btn-green' %>

<% if current_user %>
  <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: "delete" }, class:
    'btn-purple' %>
<% else %>
  <%= link_to "Login", new_user_session_path, class: 'btn-purple' %>
  <%= link_to "Register", new_user_registration_path, class: 'btn-purple' %>
<% end %>

<% if current_user && !current_user.admin? %>
  <%= render partial: 'user_dashboard', locals: {borrows_with_books: @borrows_with_books} %>
<% elsif current_user&.admin? %>
  <%= render partial: 'admin_dashboard', locals: {
    total_books: @total_books,
    total_borrowed_books: @total_borrowed_books,
    books_due_today: @books_due_today,
    members_with_overdue_books: @members_with_overdue_books,
    borrowed_books_by_due_date: @borrowed_books_by_due_date
  } %>
<% else %>
  <h1>Welcome to the Library</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>